### ISSUE TITLE
Mouse off canvas issue

### ISSUE THREAD

**Issue by Cypher1** [remvst/lost-beacons#1]
It seems navigation breaks if the mouse goes off the canvas during game play.

Love the game (Initially played it just to vote for 13k, but now I'm just playing for fun)

**Comment by remvst** [comment]
wut sorry I didn't get emails for this.
Yeah so unless the game goes fullscreen I don't think there's much that can be done about it unfortunately :(

**Comment by remvst** [comment]
Actually it seems like it is possible: https://stackoverflow.com/questions/923299/how-can-i-detect-when-the-mouse-leaves-the-window
My whole life was a lie

**Comment by hinell** [comment]
@Cypher1 I fixed that problem. Just take a look at my [fork](https://github.com/hinell/lost-beacons)
I hope you enjoy. 😉
