### ISSUE TITLE
Game freezes at later levels

### ISSUE THREAD

**Issue by extempore** [remvst/lost-beacons#3]
I've played this on both Chrome and Firefox. The game freezes indefinitely, randomly, usually after sector 10. I managed to beat sector 10 and 11 before the enemy had too many units, but then it froze mid-way through sector 12.

**Comment by remvst** [comment]
Wow how did you even get that far, I can't get past sector 5 o_O

Anyway the game isn't really optimized because of the size limitations. If I were to ever reimplement it there would be lots of room for improvement

**Comment by johnLate** [comment]
@remvst, I think it might be the line
`return maxDistance && (!cast || dist(start, cast)) > maxDistance`
in [src/js/world/world.js, `class World`, `castRay`](https://github.com/remvst/lost-beacons/blob/7b9fecc97eb86a3f026ec114c01cd274f34e0a24/src/js/world/world.js#L364)

Should it be `return maxDistance && (!cast || dist(start, cast) > maxDistance)` instead?

**Comment by remvst** [comment]
Oh good catch, seems like that part is broken indeed
